# # config file version
apiVersion: 1

notifiers:
 - name: default-email
   type: email
   org_id: 1
   uid: notifier2
   is_default: false  
   uploadImage: true
   settings:
     addresses: alert@mymonitor.com
delete_notifiers:
 - name: default-email
   uid: notifier2